---

# ---
# SLAM_TASKNAME: SYSMANGO DOCKER SERVICES PLAYBOOK
# SLAM_FACT_SYSTEM: Linux
# SLAM_Q: [ play,triage ]
# SLAM_FF_TARGET:
#   type: Integer
#   required: false
#   prompt: Enter the target
#   ghost: eg www.google.com
#   default: www.csc.com
#   tooltip: Target Name
# SLAM_FF_NUMTRIES:
#   type: Integer
#   required: true
#   prompt: Enter the Number of tries
#   default: 3
# ---

- name: Deploy docker services
  hosts: docker-manager[0]
  gather_facts: true
  roles:
  - mangonet
  - traefik-service
  - jira-service
