---

- name: Install nfs client
  become: "yes"
  zypper:
    name: nfs-client
    type: package
    state: present

- name: Setup NFS client mount point for volumes
  become: "yes"
  file:
    path: /srv/docker-volumes
    state: directory
    mode: 0777

- name: Mount NFS volume root
  become: "yes"
  mount:
    path: /srv/docker-volumes
    src: grid011.sysmango.net:/srv/nfs
    fstype: nfs
    opts: rw
    state: mounted

- name: Make sure NFS mounts will mount on startup
  become: "yes"
  service:
    name: nfs
    state: started
    enabled: "yes"

